name: Docker Build & Deploy
 
on:
    push:
    workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu_latest
    container:
        image: maven:3.9.9-eclipse-temurim-21
    steps:
        - name: Checkout código
          uses: actions/checkout@v4
 
        - name: Executar testes no container
          run: mvn -B verify
 
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
 
      - name: Login no Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
 
      - name: Build e Push para Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-links-uteis:latest
 
      - name: Deploy no Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
 